# models/marts/product/schema.yml

version: 2

models:
 - name: monthly_scores

metrics:
  - name: sum_records
    label: Salesman records
    model: ref('monthly_scores')
    description: "All records from salesman from last month last score"

    calculation_method: sum
    expression: record

    timestamp: '2023-09-06'

    window:
      count: 14
      period: day

    filters:
      - field: id_employee
        operator: '='
        value: '3'


  - name: count_records
    label: Count records
    model: ref('monthly_scores')
    description: "Count records from salesman from last month last score"

    calculation_method: count
    expression: record

    timestamp: '2023-09-06'

    window:
      count: 14
      period: day

    filters:
      - field: id_employee
        operator: '='
        value: '3'

